<div class="container-fluid h-100">
	<div class="row h-100">
    
    <div class="col-md-6 banner">
    	<div class="row h-100 justify-content-center align-items-center">
    		<div>
				<div class="communicationItem">
					<i class="fas fa-search fa-2x mr-3"></i>
					Segue o que te interessa.
				</div>
				<div class="communicationItem">
					<i class="fas fa-user-friends fa-2x mr-3"></i>
					Sabe aquilo que as pessoas estão a falar
				</div>
				<div class="communicationItem">
					<i class="far fa-comment fa-2x mr-3"></i>
					Participa em conversas.
				</div>
			</div>
		</div>
    </div>

    <div class="col-md-6 pt-4 pl-5 pr-5">
		<form method="POST" action="/autenticar">
			<div class="row">
				<div class="col">
					<input type="text" name="email" class="form-control" placeholder="E-mail">
				</div>
				<div class="col">
					<input type="password" name="senha" class="form-control" placeholder="Palavra-Passe">
				</div>
				<div class="col-auto">
					<button type="submit" class="btn btn-primary mb-2">Entrar</button>
				</div>
			</div>
			<?php if($this->view->login == 'erro') { ?>
			<div class="row">
				<div class="col">
				<span class="text text-danger">*Email ou Senha incorretos</span>
				</div>
			</div>
			<?php } ?>
		</form>

		<div class="row pt-5 pl-5 pr-5">
			<div class="col pl-5 pr-5">
				<img src="/img/twitter_logo.png" />
				<h1 class="title">Vê o que está a acontecer no mundo agora</h1>

				<h2 class="mt-5 subtitle">Cria a tua conta agora</h2>
				<a href="/inscreverse" class="btn btn-primary btn-block mb-2">Registar</a>
			</div>	
		</div>


    </div>

  </div>
</div>