<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <img src="/img/twitter_logo.png" />
        </div>

        <div class="row">
          <div class="col">
            <h2>Cria a tua conta</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">

            <form action="/registar" method="post">
              <div class="form-group">
                <input type="text" value="<?=$this->view->utilizador['nome'] ?>" name="nome" class="form-control" placeholder="Nome">
              </div>

              <div class="form-group">
                <input type="text" value="<?=$this->view->utilizador['email'] ?>" name="email" class="form-control" placeholder="E-mail">
              </div>

              <div class="form-group">
                <input type="password" value="<?=$this->view->utilizador['senha'] ?>" name="senha" class="form-control" placeholder="Palavra-Passe">
              </div>

              <div class="mt-4 mb-4">
                <small class="form-text">
                  Ao inscreveres-te, concordas com os Termos de Serviço e com as Políticas de Privacidade, incluindo o Uso de Cookies. Outras pessoas poderão encontrar-te pelo e-mail ou número de telemóvel fornecido · Opções de Privacidade
                </small>
              </div>
              <button type="submit" class="btn btn-primary btn-block">Criar Conta</button>

              <?php

              if ($this->view->erroRegisto) { ?>
                <small class="form-text text-danger">*Erro ao realizar o registo, por favor verifique novamente os campos</small>
              <?php } ?>
            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>